# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  docker-images:
    schedule:
      interval: "weekly"
  maven:
    schedule:
      interval: "weekly"
  github-actions:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: docker-images
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: maven
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows"
    patterns: ["*"]
    multi-ecosystem-group: github-actions
